import "@/styles/globals.css";
import vazirFont from "constants/localFont";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${vazirFont.variable} font-sans min-h-screen`}>
        {/* header */}
        <div>header</div>
        <div className="container xl:max-w-screen-xl">{children}</div>
      </body>
    </html>
  );
}
